name: Build Dictionaries

on: push

jobs:
  build-dicts:
    name: Build stardict dictionaries using pyglossary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: ruff format
        run: uv run ruff format --check to_dict.py

      - name: ruff check
        run: uv run ruff check to_dict.py

      - name: mypy
        run: uv run mypy --pretty to_dict.py

      - name: Build dictionaries
        # For example, using `pytest`
        run: uv run python3 to_dict.py

      - name: Package dictionaries
        run: |
          for d in dicts/*; do
          zip --junk-paths "${d#dicts/}" "${d}"/*
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
